apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gooczbx4r-python
  janus-idp.io/tekton: gooczbx4r-python
  backstage.io/kubernetes-id: gooczbx4r-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gooczbx4r-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
